version: "3"
services:
    swordfishsync:
        build:
            context: github.com/jsloane/swordfishsync
            dockerfile: Dockerfile
        container_name: SwordfishSync
        ports:
          - "8080:8080"
        restart: unless-stopped