version: "3"
services:
    swordfishsync:
        image: https://github.com/jsloane/swordfishsync.git
        container_name: swordfishsync
        ports:
          - "8080:8080"
        restart: unless-stopped